### ISSUE TITLE
In cv:: dnn + OF inference, only caffe models are possible?

### ISSUE THREAD

**Issue by bemoregt** [TetsuakiBaba/ofxOpenCvDnnObjectDetection#1]
HI, @TetsuakiBaba 

It's first OF code that using Deep inference model, I've ever seen.

In cv:: dnn + OF inference, only caffe models are possible?

I am familiar with  pytorch model (*.pth). 
Then pth model + cv::dnn is also possibel ??

I wonder. Thanks.

Best,
@bemoregt.

**Comment by TetsuakiBaba** [comment]
This addon uses OpenCV library to use CPU inference.
It seems that OpenCV handle several DNN models including pth.
Please check this link for more detail.
https://github.com/opencv/opencv/wiki/Deep-Learning-in-OpenCV

I just test, tensorflow, caffe, darknet model to be worked.
I wanna to know the result of other frameworks!!

**Comment by TetsuakiBaba** [comment]
OpenCV supports torch only on Fast-Neural-Style and OpenFace, not Object Detection.

**Comment by bemoregt** [comment]
HI, @TetsuakiBaba 

Case of caffemodel, It is not easy for my trained model's inference.

and ONNX model is also not easy converting from pytorch or keras.  )-:

Did you know the libtorch ? Libtorch is a C++ frontend of pytorch.

libtorch + OF will be a best inferencing IDE, may be.
But I not succeded to call libtorch header to OF & XCode.

Thanks.

**Comment by TetsuakiBaba** [comment]
Hi, @bemoregt 
I'm not good at using torch libraries. I could not be a help for it.
행운을 빕니다 ;-)
