### ISSUE TITLE
yolov3?

### ISSUE THREAD

**Issue by ThomasLengeling** [TetsuakiBaba/ofxOpenCvDnnObjectDetection#2]
Thank you for the great library, it worked great for me after I created a project with the projected generator. Does the library work for yolov3 and if so do you have the .weights files?, I saw on one of the examples that you used it, and I was wondering if you could share them with me or us
Anyways thank you for the great help!

**Comment by TetsuakiBaba** [comment]
Hi, it works with yolov3 weights file too. Easiest way is to download yolov3.weights from darknet website, https://pjreddie.com/darknet/yolo/ 

For Example, here is a direct link to a weights and cfg file for yolov3 model. 
https://pjreddie.com/media/files/yolov3.weights
https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov3.cfg

Please use coco class file as class label file, you can download it here: 
https://github.com/pjreddie/darknet/blob/master/data/coco.names

**Comment by ThomasLengeling** [comment]
Nice thank you!
