### ISSUE TITLE
opencv2/dnn.hpp' file not found

### ISSUE THREAD

**Issue by bitSpaz** [TetsuakiBaba/ofxOpenCvDnnObjectDetection#4]
macOS 12.6
oF 0.11 and oF 0.11.2
Xcode  13.3.1 (13E500a)

Greetings,
I would really like to work with your add-on, but I get the 'opencv2/dnn.hpp error' when trying to run the camera example. The error points to line 5 of the ofxOpenCvDnnObjectDetection.h file.

Any assistance would be appreciated.

Thanks

**Comment by bitSpaz** [comment]
It looks like Xcode can't find the opencv2.framework. The filename is red.

**Comment by TetsuakiBaba** [comment]
Hi, 

you need to build the project with ofxOpenCv.  Try following Getting Started with Examples/single_image. in the Readme.
https://github.com/TetsuakiBaba/ofxOpenCvDnnObjectDetection

**Comment by tianBreznik** [comment]
Hi! The single image works fine, but the camera still doesn't.

**Comment by TetsuakiBaba** [comment]
> Hi! The single image works fine, but the camera still doesn't.

Hi, I just checked and found out that it was due to an incorrect dnn model file referenced in ofApp.cpp. Thanks for your comment. I've already fixed the master branch, so you can try the camera example again following the instructions in the readme. 0.12.0 also works.
